FROM golang:alpine 

RUN apk add --no-cache build-base
RUN apk add --no-cache make
RUN apk add --no-cache git 
RUN apk add --no-cache bash
RUN apk add --no-cache openssl

WORKDIR /app
ADD . /app
RUN make build

EXPOSE 3000
CMD ["build/bin/rest_body_logging"]