FROM golang:alpine AS builder

RUN apk add --no-cache build-base && \
    apk add --no-cache make && \
    apk add --no-cache git  && \
    apk add --no-cache bash && \
    apk add --no-cache openssl

WORKDIR /app
ADD . /app
RUN make build

FROM alpine:latest

RUN addgroup -g 10001 -S golang && adduser -u 10000 -S -G golang -h /home/nonroot golang

WORKDIR /home/nonroot 
COPY --from=builder /app/build/bin/rest_body_logging .


USER golang
EXPOSE 3000
CMD ["./rest_body_logging"]