FROM golang:alpine AS builder

RUN apk add --no-cache build-base && \
    apk add --no-cache make && \
    apk add --no-cache git  && \
    apk add --no-cache bash && \
    apk add --no-cache openssl

WORKDIR /app
ADD . /app
RUN make build

FROM alpine:latest
WORKDIR /app/
COPY --from=builder /app/build/bin/rest_body_logging .

EXPOSE 3000
CMD ["./rest_body_logging"]